version: '3'

services:
  # Frontend
  web:
    image: jitsi/web:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${HTTP_PORT:-8000}:80'
      - '${HTTPS_PORT:-8443}:443'
    volumes:
      - ${CONFIG}/web:/config:Z
      - ${CONFIG}/web/crontabs:/var/spool/cron/crontabs:Z
      - ${CONFIG}/transcripts:/usr/share/jitsi-meet/transcripts:Z
      - ${CONFIG}/web/load-test:/usr/share/jitsi-meet/load-test:Z
    networks:
      - meet.jitsi
    depends_on:
      - jvb

  # XMPP server
  prosody:
    image: jitsi/prosody:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    expose:
      - '${XMPP_PORT:-5222}'
      - '${PROSODY_S2S_PORT:-5269}'
      - '5347'
      - '${PROSODY_HTTP_PORT:-5280}'
    volumes:
      - ${CONFIG}/prosody/config:/config:Z
      - ${CONFIG}/prosody/prosody-plugins-custom:/prosody-plugins-custom:Z
    networks:
      - meet.jitsi

  # Focus component
  jicofo:
    image: jitsi/jicofo:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    volumes:
      - ${CONFIG}/jicofo:/config:Z
    networks:
      - meet.jitsi
    depends_on:
      - prosody
    # Removed ports mapping to avoid 8888 conflict

  # Video bridge
  jvb:
    image: jitsi/jvb:${JITSI_IMAGE_VERSION:-unstable}
    restart: ${RESTART_POLICY:-unless-stopped}
    ports:
      - '${JVB_PORT:-10000}:${JVB_PORT:-10000}/udp'
      - '127.0.0.1:${JVB_COLIBRI_PORT:-8080}:8080'
    volumes:
      - ${CONFIG}/jvb:/config:Z
    networks:
      - meet.jitsi
    depends_on:
      - prosody

# Custom network so all services can communicate using a FQDN
networks:
  meet.jitsi:
